### ISSUE TITLE
the "filename" option is required to use includes and extends with "relative" paths

### ISSUE THREAD

**Issue by LiTiang** [giniedp/vscode-pug2html#2]
Hi, nice work

but there're still some issue, see below

---
says, i have 2 pug files, 
* **A.pug**
* **B.pug**

```
//- below is A.pug content
include B.pug
```

Where, 

```
//- below is B.pug content
h1 B.pug
```
now, 
execute **_vscode-pug2html_** on **A.pug**

u will see the same error as this issue title

This is important issue, 
PLEASE FIX IT AS SOON AS POSSIBLE

**Comment by giniedp** [comment]
fixed in 0.0.4
