### ISSUE TITLE
unknown configuration settings?

### ISSUE THREAD

**Issue by samumist** [giniedp/vscode-pug2html#3]
I have the following configuration settings in the `settings.json`. The editor kept complaining `Unknown configuration settings` in the PROBLEMS tab though the settings worked as expected.
```
  "pug2html.compileOptions": {
    "doctype": "html",
    "pretty": true,
    "filename": "index.pug"
  },
```

Nothing serious, just a bit annoying. 

![test css test code today at 4 02 23 pm](https://user-images.githubusercontent.com/3883086/28356746-bf2311fc-6c9b-11e7-8be7-34178f390882.png)

**Comment by giniedp** [comment]
thx, it is fixed in version 0.0.5
