### ISSUE TITLE
obj compileOption is not working

### ISSUE THREAD

**Issue by justin-calleja** [giniedp/vscode-pug2html#4]
Given the following:

```json
{
	"pug2html.compileOptions": {
		"basedir": "/Users/juca01/tmp-dir/tmpexpress",
		"pretty": true,
		"obj": "{ process: { env: { \"NODE_ENV\": \"production\" } } }"
	}
}
```

I'm expecting the contents of this condition to render:

```
if process.env.NODE_ENV === 'production'
```

But it isn't. It is if I use the compiler directly.

Thanks!

**Comment by giniedp** [comment]
`obj` ist not a compile option. At least it is not in the pug reference. 
https://pugjs.org/api/reference.html

Maybe you want to use `self` option instead? But then you have to refer to it as `self.process.env.NODE_ENV`

Here you can see how the i call the compiler
https://github.com/giniedp/vscode-pug2html/blob/master/src/extension.ts#L84

How do you call the compiler directly?

**Comment by justin-calleja** [comment]
Hi @giniedp !

Sorry about that - I'm using [pug-cli](https://github.com/pugjs/pug-cli) and assumed that the options I pass to it are directly passed to the compiler. It seems they're not from what you're telling me.

Thanks
