### ISSUE TITLE
does it have a compile on save option?

### ISSUE THREAD

**Issue by yoyoys** [giniedp/vscode-pug2html#6]
Fantastic plugin, i use it with easy less without webpack or gulp, very simple and helpful.

but i need to copy html to destination file everytime when i edited the .pug file, can you provide a option for that? 
Thanks.

**Comment by llihak** [comment]
I just found this plugin and love the idea of pug.      I also need to get it to save an output html file and can't find how to do it.     I am not a js guy.        Any suggestions?     --thanks

**Comment by giniedp** [comment]
this plugin is meant to be used as a preview tool only. Mainly to help people who are just starting with pug. If you need to save the html result i suggest to use gulp or similar tools which are able to watch your project files and transform them as you require.
